<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax;


/**
 * The role every slot of every node plays in the indentation of the lines the node spreads over.
 */
final class LayoutData
{
	/** @var array<class-string<Node>, array<string, LayoutRole>> */
	public const Roles = [
		Nodes\NameNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\IdentifierNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\ArgumentListNode::class => [
			'openParen' => LayoutRole::Anchor,
			'items' => LayoutRole::Content,
			'closeParen' => LayoutRole::Closes,
		],
		Nodes\ArgumentNode::class => [
			'name' => LayoutRole::Content,
			'colon' => LayoutRole::Content,
			'ampersand' => LayoutRole::Content,
			'ellipsis' => LayoutRole::Content,
			'value' => LayoutRole::Content,
		],
		Nodes\VariadicPlaceholderNode::class => [
			'ellipsis' => LayoutRole::Content,
		],
		Nodes\ArgumentPlaceholderNode::class => [
			'name' => LayoutRole::Content,
			'colon' => LayoutRole::Content,
			'question' => LayoutRole::Content,
		],
		Nodes\AttributeGroupNode::class => [
			'openAttribute' => LayoutRole::Anchor,
			'attributes' => LayoutRole::Content,
			'closeBracket' => LayoutRole::Closes,
		],
		Nodes\AttributeNode::class => [
			'name' => LayoutRole::Content,
			'arguments' => LayoutRole::Content,
		],
		Nodes\ModifiersNode::class => [
			'tokens' => LayoutRole::Anchor,
		],
		Nodes\NodeList::class => [
			'items' => LayoutRole::Content,
		],
		Nodes\SeparatedNodeList::class => [
			'items' => LayoutRole::Content,
			'separators' => LayoutRole::Content,
		],
		Nodes\FileNode::class => [
			'statements' => LayoutRole::Anchor,
			'endOfFile' => LayoutRole::Anchor,
		],
		Nodes\ArrayItemNode::class => [
			'key' => LayoutRole::Content,
			'doubleArrow' => LayoutRole::Content,
			'ampersand' => LayoutRole::Content,
			'ellipsis' => LayoutRole::Content,
			'value' => LayoutRole::Content,
		],
		Nodes\EmptyArrayItemNode::class => [],
		Nodes\MatchArmNode::class => [
			'values' => LayoutRole::Anchor,
			'defaultKeyword' => LayoutRole::Anchor,
			'defaultComma' => LayoutRole::Content,
			'doubleArrow' => LayoutRole::Content,
			'body' => LayoutRole::Content,
		],
		Nodes\Expression\VariableNode::class => [
			'dollar' => LayoutRole::Content,
			'openBrace' => LayoutRole::Anchor,
			'name' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
		],
		Nodes\Expression\ArrayAccessNode::class => [
			'expression' => LayoutRole::Content,
			'openBracket' => LayoutRole::Anchor,
			'index' => LayoutRole::Content,
			'closeBracket' => LayoutRole::Closes,
		],
		Nodes\Expression\PropertyFetchNode::class => [
			'object' => LayoutRole::Content,
			'operator' => LayoutRole::Link,
			'openBrace' => LayoutRole::Anchor,
			'name' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
		],
		Nodes\Expression\StaticPropertyFetchNode::class => [
			'class' => LayoutRole::Content,
			'doubleColon' => LayoutRole::Content,
			'dollar' => LayoutRole::Content,
			'openBrace' => LayoutRole::Anchor,
			'name' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
		],
		Nodes\Expression\ClassConstantFetchNode::class => [
			'class' => LayoutRole::Content,
			'doubleColon' => LayoutRole::Content,
			'openBrace' => LayoutRole::Anchor,
			'name' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
		],
		Nodes\Expression\ConstantFetchNode::class => [
			'name' => LayoutRole::Content,
		],
		Nodes\Expression\FunctionCallNode::class => [
			'name' => LayoutRole::Content,
			'arguments' => LayoutRole::Content,
		],
		Nodes\Expression\MethodCallNode::class => [
			'object' => LayoutRole::Content,
			'operator' => LayoutRole::Link,
			'openBrace' => LayoutRole::Anchor,
			'name' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
			'arguments' => LayoutRole::Content,
		],
		Nodes\Expression\StaticMethodCallNode::class => [
			'class' => LayoutRole::Content,
			'doubleColon' => LayoutRole::Content,
			'openBrace' => LayoutRole::Anchor,
			'name' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
			'arguments' => LayoutRole::Content,
		],
		Nodes\Expression\ArrayNode::class => [
			'arrayKeyword' => LayoutRole::Anchor,
			'openDelimiter' => LayoutRole::Anchor,
			'items' => LayoutRole::Content,
			'closeDelimiter' => LayoutRole::Closes,
		],
		Nodes\Expression\ListNode::class => [
			'listKeyword' => LayoutRole::Anchor,
			'openDelimiter' => LayoutRole::Anchor,
			'items' => LayoutRole::Content,
			'closeDelimiter' => LayoutRole::Closes,
		],
		Nodes\Expression\AssignmentNode::class => [
			'target' => LayoutRole::Content,
			'operator' => LayoutRole::Content,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\CombinedAssignmentNode::class => [
			'target' => LayoutRole::Content,
			'operator' => LayoutRole::Content,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\AssignmentByReferenceNode::class => [
			'target' => LayoutRole::Content,
			'equals' => LayoutRole::Content,
			'ampersand' => LayoutRole::Content,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\BinaryOpNode::class => [
			'left' => LayoutRole::Content,
			'operator' => LayoutRole::Operator,
			'right' => LayoutRole::Operator,
		],
		Nodes\Expression\UnaryOpNode::class => [
			'operator' => LayoutRole::Content,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\PrefixOpNode::class => [
			'operator' => LayoutRole::Content,
			'target' => LayoutRole::Content,
		],
		Nodes\Expression\PostfixOpNode::class => [
			'target' => LayoutRole::Content,
			'operator' => LayoutRole::Content,
		],
		Nodes\Expression\CastNode::class => [
			'cast' => LayoutRole::Content,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\TernaryNode::class => [
			'condition' => LayoutRole::Content,
			'question' => LayoutRole::Branch,
			'then' => LayoutRole::Branch,
			'colon' => LayoutRole::Branch,
			'else' => LayoutRole::Branch,
		],
		Nodes\Expression\InstanceofNode::class => [
			'expression' => LayoutRole::Content,
			'instanceofKeyword' => LayoutRole::Operator,
			'class' => LayoutRole::Operator,
		],
		Nodes\Expression\ParenthesizedNode::class => [
			'openParen' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
			'closeParen' => LayoutRole::Closes,
		],
		Nodes\Expression\IssetNode::class => [
			'issetKeyword' => LayoutRole::Anchor,
			'openParen' => LayoutRole::Anchor,
			'variables' => LayoutRole::Content,
			'closeParen' => LayoutRole::Closes,
		],
		Nodes\Expression\EmptyNode::class => [
			'emptyKeyword' => LayoutRole::Anchor,
			'openParen' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
			'closeParen' => LayoutRole::Closes,
		],
		Nodes\Expression\EvalNode::class => [
			'evalKeyword' => LayoutRole::Anchor,
			'openParen' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
			'closeParen' => LayoutRole::Closes,
		],
		Nodes\Expression\IncludeNode::class => [
			'includeKeyword' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\ExitNode::class => [
			'exitKeyword' => LayoutRole::Anchor,
			'arguments' => LayoutRole::Content,
		],
		Nodes\Expression\PrintNode::class => [
			'printKeyword' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\YieldNode::class => [
			'yieldKeyword' => LayoutRole::Anchor,
			'key' => LayoutRole::Content,
			'doubleArrow' => LayoutRole::Content,
			'value' => LayoutRole::Content,
		],
		Nodes\Expression\YieldFromNode::class => [
			'yieldFromKeyword' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\ThrowNode::class => [
			'throwKeyword' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\CloneNode::class => [
			'cloneKeyword' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
		],
		Nodes\Expression\MatchNode::class => [
			'matchKeyword' => LayoutRole::Anchor,
			'openParen' => LayoutRole::Anchor,
			'subject' => LayoutRole::Content,
			'closeParen' => LayoutRole::Closes,
			'openBrace' => LayoutRole::Anchor,
			'arms' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
		],
		Nodes\Expression\ShellExecNode::class => [
			'openBacktick' => LayoutRole::Anchor,
			'parts' => LayoutRole::Content,
			'closeBacktick' => LayoutRole::Closes,
		],
		Nodes\Scalar\IntegerNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\FloatNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\BooleanNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\NullNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\StringNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\UnquotedStringNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\MagicConstantNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\InterpolatedStringNode::class => [
			'openQuote' => LayoutRole::Anchor,
			'parts' => LayoutRole::Content,
			'closeQuote' => LayoutRole::Closes,
		],
		Nodes\Scalar\HeredocNode::class => [
			'openDelimiter' => LayoutRole::Anchor,
			'parts' => LayoutRole::Content,
			'closeDelimiter' => LayoutRole::Closes,
		],
		Nodes\Scalar\InterpolatedStringPartNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\Scalar\InterpolationNode::class => [
			'openBrace' => LayoutRole::Anchor,
			'expression' => LayoutRole::Content,
			'closeBrace' => LayoutRole::Closes,
		],
		Nodes\Type\NamedTypeNode::class => [
			'name' => LayoutRole::Content,
		],
		Nodes\Type\NullableTypeNode::class => [
			'question' => LayoutRole::Content,
			'type' => LayoutRole::Content,
		],
		Nodes\Type\UnionTypeNode::class => [
			'types' => LayoutRole::Anchor,
		],
		Nodes\Type\IntersectionTypeNode::class => [
			'openParen' => LayoutRole::Anchor,
			'types' => LayoutRole::Anchor,
			'closeParen' => LayoutRole::Closes,
		],
	];
}
