<?php declare(strict_types=1);

/**
 * @generated by grammar/build.php from grammar/nodes.php, do not edit.
 */

namespace PhpSyntax;


/**
 * The role every slot of every node plays in the indentation of the lines the node spreads over.
 */
final class LayoutData
{
	/** @var array<class-string<Node>, array<string, LayoutRole>> */
	public const Roles = [
		Nodes\NameNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\IdentifierNode::class => [
			'token' => LayoutRole::Content,
		],
		Nodes\ArgumentListNode::class => [
			'openParen' => LayoutRole::Anchor,
			'items' => LayoutRole::Content,
			'closeParen' => LayoutRole::Closes,
		],
		Nodes\ArgumentNode::class => [
			'name' => LayoutRole::Content,
			'colon' => LayoutRole::Content,
			'ampersand' => LayoutRole::Content,
			'ellipsis' => LayoutRole::Content,
			'value' => LayoutRole::Content,
		],
		Nodes\VariadicPlaceholderNode::class => [
			'ellipsis' => LayoutRole::Content,
		],
		Nodes\ArgumentPlaceholderNode::class => [
			'name' => LayoutRole::Content,
			'colon' => LayoutRole::Content,
			'question' => LayoutRole::Content,
		],
		Nodes\AttributeGroupNode::class => [
			'openAttribute' => LayoutRole::Anchor,
			'attributes' => LayoutRole::Content,
			'closeBracket' => LayoutRole::Closes,
		],
		Nodes\AttributeNode::class => [
			'name' => LayoutRole::Content,
			'arguments' => LayoutRole::Content,
		],
		Nodes\ModifiersNode::class => [
			'tokens' => LayoutRole::Anchor,
		],
		Nodes\NodeList::class => [
			'items' => LayoutRole::Content,
		],
		Nodes\SeparatedNodeList::class => [
			'items' => LayoutRole::Content,
			'separators' => LayoutRole::Content,
		],
		Nodes\FileNode::class => [
			'statements' => LayoutRole::Anchor,
			'endOfFile' => LayoutRole::Anchor,
		],
		Nodes\Type\NamedTypeNode::class => [
			'name' => LayoutRole::Content,
		],
		Nodes\Type\NullableTypeNode::class => [
			'question' => LayoutRole::Content,
			'type' => LayoutRole::Content,
		],
		Nodes\Type\UnionTypeNode::class => [
			'types' => LayoutRole::Anchor,
		],
		Nodes\Type\IntersectionTypeNode::class => [
			'openParen' => LayoutRole::Anchor,
			'types' => LayoutRole::Anchor,
			'closeParen' => LayoutRole::Closes,
		],
	];
}
