#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 * Generates the reference: nodes.md from grammar/nodes.php and the node classes.
 * Run by `composer reference`; the output is committed and CI diffs it.
 */

use PhpSyntax\LayoutData;

require __DIR__ . '/../../vendor/autoload.php';


/** Text safe inside a table cell: a pipe would split it, a tag would be swallowed. */
function markdown(string $text): string
{
	return str_replace(['|', '<'], ['\|', '&lt;'], $text);
}


/**
 * The text of a class docblock without its frame and tags.
 * @param ReflectionClass<object> $class
 */
function describeClass(ReflectionClass $class): string
{
	$lines = [];
	foreach (preg_split('~\r\n|\r|\n~', (string) $class->getDocComment()) as $line) {
		$line = trim($line, " \t/*");
		if ($line !== '' && !str_starts_with($line, '@')) {
			$lines[] = $line;
		}
	}

	return implode(' ', $lines);
}


/** A class name relative to PhpSyntax\Nodes, or to PhpSyntax for the base classes. */
function relativeClassName(string $class): string
{
	return preg_replace('~^PhpSyntax\\\(Nodes\\\)?~', '', $class);
}


/** @var array<string, array{slots?: array<string, string>, manual?: bool}> $nodes */
$nodes = require __DIR__ . '/../../grammar/nodes.php';
$out = "# Nodes\n\nGenerated by `composer reference` from grammar/nodes.php and the node classes; do not edit. "
	. count($nodes) . ' node classes under `PhpSyntax\Nodes`; a slot type is `Token`, a node class, `?` when optional, '
	. '`A|B` for a choice, `NodeList<T>` or `SeparatedNodeList<T>` for a list. The layout role is what the slot is to the '
	. "indentation of the lines the node spreads over (`PhpSyntax\\LayoutRole`).\n\n";
foreach ($nodes as $class => $node) {
	$name = 'PhpSyntax\Nodes\\' . $class;
	if (!class_exists($name)) {
		throw new Exception("The schema names $name, which does not exist; run composer build.");
	}

	$reflection = new ReflectionClass($name);
	$out .= "## $class\n\n";
	$description = describeClass($reflection);
	$out .= $description === '' ? '' : $description . "\n\n";
	$facts = [];
	if ($parent = $reflection->getParentClass()) {
		$facts[] = 'Extends `' . relativeClassName($parent->getName()) . '`';
	}

	$interfaces = array_filter($reflection->getInterfaceNames(), fn($i) => str_starts_with($i, 'PhpSyntax\\'));
	if ($interfaces) {
		$facts[] = 'Implements ' . implode(', ', array_map(fn($i) => '`' . relativeClassName($i) . '`', $interfaces));
	}

	if (!empty($node['manual'])) {
		$facts[] = 'Handwritten class';
	}

	if ($facts) {
		$out .= implode('. ', $facts) . ".\n\n";
	}

	if (!empty($node['slots'])) {
		$out .= "| Slot | Type | Layout |\n|---|---|---|\n";
		foreach ($node['slots'] as $slot => $type) {
			$role = LayoutData::Roles['PhpSyntax\Nodes\\' . $class][$slot];
			$out .= sprintf("| `%s` | `%s` | %s |\n", $slot, markdown($type), $role->name);
		}

		$out .= "\n";
	}
}

file_put_contents(__DIR__ . '/nodes.md', $out);
echo 'nodes.md: ', count($nodes), " node classes\n";
